[package]
name = "pg_bigdecimal"
authors = ["Rick Klomp <rick.klomp@tzconnect.com>"]
version = "0.1.0"
edition = "2018"
license = "MIT"
keywords = ["postgres", "pg", "numeric", "bigdecimal"]
categories = ["database"]
include = ["/src", "/test_with_tempdb.bash"]
publish = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
bigdecimal = "0.3.0"
byteorder = "1.4.3"
num = "0.4"
postgres = "0.19.1"
